---
title: "Merging data for CCNA Phase 1a and Phase 1b"
output: html_document
---

##### Preparing csv files for merging
  
1. For 1b, created new header row, getting rid of all spaces and other special characters like + - * (find and replace with '.' or nothing at all). Note to self: In Excel, ? and * in "Replace" act as wildcards and will replace every character! 
 
2. For 1b, copied and pasted just the filled cells into another new sheet; for some reason the original file had an enormous size of 54 MB and expanded to 253 MB as a csv (even though there were only 238 participants), likely because of extra blank rows/columns.
 
3. For 1b, deleted first and last name columns. 
 
4. For 1a, copied and pasted values into a new sheet and saved as csv file.
 
5. For both 1a and 1b, copied participant ID column and gave it the same header "PPT" in both. This will be used for matching.
 
##### Code for merging
Note that all blank cells are now indicated by NA.
```{r}
ccna_1a <- read.csv("/Users/huiwen/Documents/Research/Digit Triplets Test/DTT CCNA/data_2020_04_20/merging/ccna_1a.csv", header=T, na.strings=c(""))

ccna_1b <- read.csv("/Users/huiwen/Documents/Research/Digit Triplets Test/DTT CCNA/data_2020_04_20/merging/ccna_1b.csv", header=T, na.strings=c(""))

ccna_1b_1a <- merge(ccna_1b, ccna_1a, by.x = "PPT", by.y = "PPT", all.x = TRUE, all.y = FALSE, sort = FALSE)

write.csv(ccna_1b_1a, "~/Desktop/ccna_1b_1a.csv")

```

